# Generated by Django 3.1.7 on 2021-08-29 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('column_separator', models.CharField(choices=[(',', 'Comma(,)'), (':', 'Semicolon(:)'), ('|', 'Pipe(|)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[("'", "Single-quote(')"), ('"', 'Double-quote (")')], default="'", max_length=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], default='Processing', max_length=11)),
                ('created', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('column_type', models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Company', 'Company'), ('Integer', 'Integer')], default='Full name', max_length=10)),
                ('start_value', models.IntegerField(blank=True, null=True)),
                ('end_value', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.schema')),
            ],
        ),
    ]
