# Generated by Django 3.1.7 on 2021-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='has_range',
            field=models.BooleanField(default=False),
        ),
    ]
