# Generated by Django 3.1.7 on 2021-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0002_column_has_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='column_type',
        ),
        migrations.AddField(
            model_name='column',
            name='colummn_type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Company', 'Company'), ('Integer', 'Integer')], default='Integer', max_length=10),
        ),
    ]
