# Generated by Django 3.1.7 on 2021-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0003_auto_20210830_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='colummn_type',
            new_name='column_type',
        ),
    ]
