# Generated by Django 3.1.7 on 2021-09-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0005_remove_column_has_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('-id',)},
        ),
    ]
